import express from 'express';
import multer from 'multer';
import { s3Service } from '../services/S3Service';
import { dataStorageService } from '../services/DataStorageService';
import { authenticate, authorize } from '../middleware/auth';
import { logger } from '../utils/logger';

const router = express.Router();

// Configure multer for file uploads
const upload = multer({
  storage: multer.memoryStorage(),
  limits: {
    fileSize: 10 * 1024 * 1024 // 10MB limit
  },
  fileFilter: (req, file, cb) => {
    // Allow common file types
    const allowedTypes = [
      'image/jpeg',
      'image/png',
      'image/gif',
      'application/pdf',
      'text/plain',
      'text/csv',
      'application/json',
      'text/markdown'
    ];
    
    if (allowedTypes.includes(file.mimetype)) {
      cb(null, true);
    } else {
      cb(new Error('File type not allowed'));
    }
  }
});

/**
 * Upload file to S3
 */
router.post('/upload', authenticate, upload.single('file'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No file provided' });
    }

    const { folder } = req.body;
    
    const result = await s3Service.uploadFile(
      req.file.buffer,
      req.file.originalname,
      req.file.mimetype,
      folder
    );

    logger.info(`File uploaded by user ${req.user?.id}: ${result.key}`);

    res.json({
      success: true,
      data: result
    });
  } catch (error) {
    logger.error('File upload failed:', error);
    res.status(500).json({
      error: 'File upload failed',
      message: (error as Error).message
    });
  }
});

/**
 * Get signed URL for file download
 */
router.get('/download/:key(*)', authenticate, async (req, res) => {
  try {
    const { key } = req.params;
    const { expires } = req.query;
    
    const signedUrl = await s3Service.getSignedUrl(
      key, 
      expires ? parseInt(expires as string) : undefined
    );

    res.json({
      success: true,
      data: { signedUrl }
    });
  } catch (error) {
    logger.error('Failed to generate signed URL:', error);
    res.status(500).json({
      error: 'Failed to generate download URL',
      message: (error as Error).message
    });
  }
});

/**
 * List files in a folder
 */
router.get('/files', authenticate, async (req, res) => {
  try {
    const { folder, maxKeys } = req.query;
    
    const files = await s3Service.listFiles(
      folder as string,
      maxKeys ? parseInt(maxKeys as string) : undefined
    );

    res.json({
      success: true,
      data: { files }
    });
  } catch (error) {
    logger.error('Failed to list files:', error);
    res.status(500).json({
      error: 'Failed to list files',
      message: (error as Error).message
    });
  }
});

/**
 * Delete file from S3
 */
router.delete('/files/:key(*)', authenticate, authorize(['admin', 'manager']), async (req, res) => {
  try {
    const { key } = req.params;
    
    await s3Service.deleteFile(key);
    
    logger.info(`File deleted by user ${req.user?.id}: ${key}`);

    res.json({
      success: true,
      message: 'File deleted successfully'
    });
  } catch (error) {
    logger.error('Failed to delete file:', error);
    res.status(500).json({
      error: 'Failed to delete file',
      message: (error as Error).message
    });
  }
});

/**
 * Upload knowledge base article
 */
router.post('/knowledge-base', authenticate, authorize(['admin', 'manager']), async (req, res) => {
  try {
    const { title, content, category } = req.body;
    
    if (!title || !content || !category) {
      return res.status(400).json({
        error: 'Title, content, and category are required'
      });
    }

    const key = await dataStorageService.storeKnowledgeBaseArticle(title, content, category);
    
    logger.info(`Knowledge base article created by user ${req.user?.id}: ${title}`);

    res.json({
      success: true,
      data: { key, title, category }
    });
  } catch (error) {
    logger.error('Failed to create knowledge base article:', error);
    res.status(500).json({
      error: 'Failed to create knowledge base article',
      message: (error as Error).message
    });
  }
});

/**
 * Generate and store report
 */
router.post('/reports', authenticate, authorize(['admin', 'manager']), async (req, res) => {
  try {
    const { reportType, data, format } = req.body;
    
    if (!reportType || !data) {
      return res.status(400).json({
        error: 'Report type and data are required'
      });
    }

    const key = await dataStorageService.generateAndStoreReport(reportType, data);
    
    logger.info(`Report generated by user ${req.user?.id}: ${reportType}`);

    res.json({
      success: true,
      data: { key, reportType }
    });
  } catch (error) {
    logger.error('Failed to generate report:', error);
    res.status(500).json({
      error: 'Failed to generate report',
      message: (error as Error).message
    });
  }
});

/**
 * Get storage metrics
 */
router.get('/metrics', authenticate, authorize(['admin']), async (req, res) => {
  try {
    const metrics = await dataStorageService.getStorageMetrics();

    res.json({
      success: true,
      data: metrics
    });
  } catch (error) {
    logger.error('Failed to get storage metrics:', error);
    res.status(500).json({
      error: 'Failed to get storage metrics',
      message: (error as Error).message
    });
  }
});

/**
 * Storage health check
 */
router.get('/health', authenticate, async (req, res) => {
  try {
    const health = await dataStorageService.healthCheck();

    res.json({
      success: true,
      data: health
    });
  } catch (error) {
    logger.error('Storage health check failed:', error);
    res.status(500).json({
      error: 'Storage health check failed',
      message: (error as Error).message
    });
  }
});

/**
 * Archive old data
 */
router.post('/archive', authenticate, authorize(['admin']), async (req, res) => {
  try {
    const { daysOld } = req.body;
    
    await dataStorageService.archiveOldData(daysOld);
    
    logger.info(`Data archival initiated by user ${req.user?.id}`);

    res.json({
      success: true,
      message: 'Data archival completed'
    });
  } catch (error) {
    logger.error('Data archival failed:', error);
    res.status(500).json({
      error: 'Data archival failed',
      message: (error as Error).message
    });
  }
});

export default router;